<a href="https://colab.research.google.com/github/mib-a/AI-ML-Learning/blob/main/mib-a/AI-ML-Learning/Month-03-Deep-Learning/Module-11/Breast_Cancer_Python_Training_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 11.3 Data Loading and Basic Preprocessing

## Import Libraries

In [134]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [135]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


Little About the Neural Architecture:

input = 30, neuron = 1, ACT = Sigmoid, Output = y_pred

In [136]:
df.shape

(569, 33)

### Dropping Unnecessary Cols (reducing Dimensionality)

In [137]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [138]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


## Train Test Split

In [139]:
# X = df.drop(columns=['diagnosis'])
# y = df['diagnosis']
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2, random_state = 42)

## Preprocessing

### Scaling (neural models perform better when the data are scaled)

In [140]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [141]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

### Label Encoding (Encoding the M/B target dataset)

In [142]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [143]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,

### Numpy arrays to PyTorch tensors (To use PyTorch Training Pipelines)

In [144]:
type(X_train)

numpy.ndarray

So that's a numpy array, all the variables here are numpy arrays. But to use PyTorch Training Pipeline they need to be transferred into PyTorch Tensors.

In [145]:
# transformed_tensor_var = torch.tensor(numpy_array_name)

X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)


In [146]:
type(X_train_tensor)

torch.Tensor

In [147]:
X_train_tensor.shape # (row, col)

torch.Size([455, 30])

In [148]:
y_train_tensor.shape # (row) as col 1 only

torch.Size([455])

## Defining the Model

In [149]:
X_train_tensor.shape

torch.Size([455, 30])

In [150]:
class MySimpleNN():

  def __init__(self, X): # constructor (self(to call w & b), input)
    # initializing weight (size: (30*1)) (to match the matmul operation without Transpose matrix)
    self.weights = torch.rand(X.shape[1], # num of rows = no of input/cols (num of col in input dataset)
                              1, # num of col = 1 # as all features going to only one neuron
                              dtype=torch.float64, # must be float, gradient of int type can't be calculated
                              requires_grad=True)  # keeps track

    # initializing bias (1*1)
    self.bias = torch.zeros(1, # 1 element matrix for the only one neuron
                            dtype=torch.float64,
                            requires_grad=True)

  def forward(self, X): # (self, input); Z = WX + b
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):

    # Clamp predictions to avoid log(0) or log(1) respective to undefined or 0.
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon) # var = torch.clamp(var, min, max)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


You can check the weights and biases after training the pipeline

### Important Parameters (lr and epoch)

In [151]:
learning_rate = 0.1
epochs = 25

## Training Pipeline

In [152]:
# create model
model = MySimpleNN(X_train_tensor) # training the model on train dataset

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update: so it renew every time ~ = the loop doesnt change the values each time of w_old.
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}') # epoch + 1 as count starts from zero

Epoch: 1, Loss: 3.0361871941075496
Epoch: 2, Loss: 2.898873636105541
Epoch: 3, Loss: 2.7542220679039713
Epoch: 4, Loss: 2.6053572228172994
Epoch: 5, Loss: 2.455029701115578
Epoch: 6, Loss: 2.3034081063657603
Epoch: 7, Loss: 2.15336268167628
Epoch: 8, Loss: 2.005772376312471
Epoch: 9, Loss: 1.8584535106092612
Epoch: 10, Loss: 1.71683735974833
Epoch: 11, Loss: 1.583454320269862
Epoch: 12, Loss: 1.4620997979773669
Epoch: 13, Loss: 1.3538509186458472
Epoch: 14, Loss: 1.259383356414871
Epoch: 15, Loss: 1.178867110259505
Epoch: 16, Loss: 1.1119527213348397
Epoch: 17, Loss: 1.057757505918084
Epoch: 18, Loss: 1.0148318528480593
Epoch: 19, Loss: 0.9812247336655828
Epoch: 20, Loss: 0.9547637868480685
Epoch: 21, Loss: 0.9334451049309215
Epoch: 22, Loss: 0.9156920545725192
Epoch: 23, Loss: 0.900396315755285
Epoch: 24, Loss: 0.8868288818564756
Epoch: 25, Loss: 0.8745250458539205


In [153]:
model.weights
model.bias

tensor([-0.1947], dtype=torch.float64, requires_grad=True)

## Evaluation

In [154]:
y_pred # only printing the 30th element to avoid the whole list.

tensor([[0.2171],
        [0.6024],
        [0.9346],
        [0.8570],
        [0.9517],
        [0.7397],
        [0.8820],
        [0.1676],
        [0.4838],
        [0.2356],
        [0.7303],
        [0.2816],
        [0.2352],
        [0.6888],
        [0.2104],
        [0.4945],
        [0.2071],
        [0.6895],
        [0.3095],
        [0.7832],
        [0.0412],
        [0.3808],
        [0.2312],
        [0.9163],
        [0.2287],
        [0.5052],
        [0.4681],
        [0.4200],
        [0.1365],
        [0.0897],
        [0.4282],
        [0.6789],
        [0.4791],
        [0.6672],
        [0.4069],
        [0.0967],
        [0.4013],
        [0.3366],
        [0.3822],
        [0.4051],
        [0.6636],
        [0.1835],
        [0.6098],
        [0.8110],
        [0.1811],
        [0.3365],
        [0.9927],
        [0.2059],
        [0.4622],
        [0.2904],
        [0.9614],
        [0.3223],
        [0.2377],
        [0.8304],
        [0.8958],
        [0

Notice how y_pred is also tracking. We've already seen this in the computational graph. After sigmoid operation we get y_pred. So y_pred is also in requires_grad.

In [155]:
# model evaluation
with torch.no_grad(): # y_pred is also tracking so it will change the value with each loop; that's why the whole thing needs to be under no_grad()
  y_pred = model.forward(X_test_tensor) # getting the y_pred tensor
  y_pred = (y_pred > 0.9).float() # y_pred True if greater than 0.9. Then applying float to convert it to 0/1 (as accuracy range is 0 to 1)
  # accuracy = all true assumptions/ all assumptions
  accuracy = (y_pred == y_test_tensor).float().mean() # accuracy = if y_pred = y (T/F); then converting to float. Then the mean of all the 1 + 0! (! Dividing by all assumptions means mean)
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.6077254414558411


In [156]:
accuracy

tensor(0.6077)

Only writing accuracy will give u a result like this. To access the values from the tensor, we use item. Like
`
accuracy.item()
`

In [157]:
y_pred # y_pred = (y_pred > 0.9 ).float()

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
      