<a href="https://colab.research.google.com/github/mib-a/AI-ML-Learning/blob/main/mib-a/AI-ML-Learning/Month-03-Deep-Learning/Module-15/15_DataSet_%26_DataLoader_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating the Dataset
- TensorDataset: Python already has given u the dataset class
- CustomDataset: You have to create your own DataSet Class

## TensorDataset Example

(Pytorch already have given the DataSet Class)

In [19]:
import torch
from torch.utils.data import TensorDataset, DataLoader

In [21]:
# Dummy Dataset
features = torch.tensor([
    [1.0,2.0], # sample 1
     [3.0,4.0], # sample 2
      [5.0,6.0] # sample 3
    ])
labels = torch.tensor([
    0, # label for sample 1
    1, # label for sample 1
    0 # label for sample 3
    ])

# Making the dataset (sample, label)
dataset = TensorDataset(features, labels)
print(f"Integrating features and Labels together to make the dataset \n(2nd sample): {dataset[1]}\n") # integrating features and labels together

# dataloader
# you can change the num of batches and play urself
dataloader = DataLoader (dataset,
                         batch_size = 2, # 2 will be processed at a time
                         shuffle = True) # batches are randomized/shuffled

# Going through the dataset batch by batch
for batch in dataloader :
  features , label = batch # batch = features, label = batch[0], batch[1]
  print("feature :", features)
  print("label :", label)

Integrating features and Labels together to make the dataset 
(2nd sample): (tensor([3., 4.]), tensor(1))

feature : tensor([[3., 4.],
        [5., 6.]])
label : tensor([1, 0])
feature : tensor([[1., 2.]])
label : tensor([0])


## Custom Dataset

In [1]:
from sklearn.datasets import make_classification

features and labels making

In [2]:
X,y = make_classification( # make_classification gives you (features, target)
    n_samples = 10, # total num of samaples
    n_features=2, # 2 features # shape of X = (10, 2)
    n_informative=2, # how many featues are incluencing the result? like t shirt size wont contibute to ur marks
    n_redundant=0, # duplicated or almost duplicated features
    n_classes=2, # two possible results (0, 1)
    random_state=42 # reproducibility
)

In [22]:
# print(X)
print(X.shape)

(10, 2)


In [5]:
y # labels

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

### Custom Dataset building the class

In [7]:
from torch.utils.data import Dataset,DataLoader # creates CUstomDataset, feeds data to model in batches

In [8]:
class CustomDataset(Dataset): # class creation
  def __init__( self,features,labels): # constructor
    self.features = features # Take the features that were given to me and store them inside this Dataset object under the name self.features
    self.labels = labels

  def __len__(self): # len(Dataset) will give u the len quickly ~= num of rows
    return self.features.shape[0]

  def __getitem__(self,index): # gives sample acc to index number
    return self.features[index], self.labels[index]


In [9]:
dataset = CustomDataset(X,y) # creatin the dataset
# Dataset's features, labels = (X, y) # X, y has been defined earlier

__len__ Function

In [10]:
#len
len(dataset) # returns self.features.shape[0]

10

__getitem__ function

In [11]:
dataset[2] # returns self.features[2], self, labels[2]

(array([-2.8953973 ,  1.97686236]), np.int64(0))

### DataLoader

In [13]:
dataloader = DataLoader(dataset,
                        batch_size=4,
                        shuffle=False)

# dataloader uses dataset.__len__() & dataset.__getitem___() to access the
# samples. %%

In [14]:
for batch_feature, batch_label in dataloader: # go through the dataloader one batch (features, labels) at a time
  print(batch_feature) # 4, 4, 2
  print(batch_label)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606]], dtype=torch.float64)
tensor([1, 0, 0, 0])
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116]], dtype=torch.float64)
tensor([0, 1, 1, 1])
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]], dtype=torch.float64)
tensor([1, 0])
