<a href="https://colab.research.google.com/github/mib-a/AI-ML-Learning/blob/main/mib-a/AI-ML-Learning/Month-03-Deep-Learning/Backpropagation%20/Module-09/Tensor_by_Torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensor by Torch

## Importing & Model No

In [1]:
import torch # importing the library, by default in colab, otherwise u had to install it and then import
print(f"Torch Version + CUDA Version = {torch.__version__}") # which version are you importing? -> output: torch_version+CUDA_version
print("CUDA is a programming language for GPU. Uses parallelism, this Version.")

Torch Version + CUDA Version = 2.11.0+cu128
CUDA is a programming language for GPU. Uses parallelism, this Version.


## Device Agnostic Code
Display which device you are on. Important for Research Papers.

In [2]:
if torch.cuda.is_available(): # if CUDA works on that, u have GPU available.
  print("GPU is available")
  print(f"Device Name: {torch.cuda.get_device_name(0)}") # you can write get_device_name(); without the zero, still prints the same
else:
  print("GPU is not available") # CUDA is not working

GPU is available
Device Name: Tesla T4


## Tensor
Tensor is just a data structure like Numpy Array. A multi dimensional array.

90% are transferable. 10% PyTorch Specific. SO learning them is kinda unnecessary.


### Interoperability & Zero-Copy Conversion

PyTorch and NumPy can share memory directly when running on CPU. This means converting between them takes **zero extra memory** and happens instantaneously.

```python
import numpy as np
import torch

# NumPy -> PyTorch (Shares memory buffer)
np_arr = np.array([1.0, 2.0, 3.0])
torch_tensor = torch.from_numpy(np_arr)

# PyTorch -> NumPy (Shares memory buffer)
torch_tensor = torch.tensor([1.0, 2.0, 3.0])
np_arr = torch_tensor.numpy()

```

##For Example
# Python vs. NumPy vs. PyTorch Equivalents

| Category | Math / Operation | Python (Built-in / `math`) | NumPy (`np.ndarray`) | PyTorch (`torch.Tensor`) |
| :--- | :--- | :--- | :--- | :--- |
| **Creation** | Array / Tensor Creation | `[1, 2, 3]` | `np.array([1, 2, 3])` | `torch.tensor([1, 2, 3])` |
| | Range | `range(0, 10)` | `np.arange(0, 10)` | `torch.arange(0, 10)` |
| | Zero / Ones Array | — | `np.zeros((3, 3))` | `torch.zeros((3, 3))` |
| **Element-wise** | Addition | `a + b` | `a + b` or `np.add(a, b)` | `a + b` or `torch.add(a, b)` |
| | Multiplication | `a * b` | `a * b` or `np.multiply(a, b)` | `a * b` or `torch.mul(a, b)` |
| | Power | `a ** b` | `a ** b` or `np.power(a, b)` | `a ** b` or `torch.pow(a, b)` |
| **Reduction** | Sum | `sum(list)` | `arr.sum()` or `np.sum(arr)` | `tensor.sum()` or `torch.sum(tensor)` |
| | Mean | `statistics.mean(list)` | `arr.mean()` or `np.mean(arr)` | `tensor.mean()` or `torch.mean(tensor)` |
| | Max Index | — | `np.argmax(arr)` | `tensor.argmax()` or `torch.argmax(tensor)` |
| **Reshaping** | Reshape Array | — | `arr.reshape(2, 3)` | `tensor.reshape(2, 3)` or `tensor.view(2, 3)` |
| | Add Dimension | `list` nesting | `arr[:, np.newaxis]` or `np.expand_dims` | `tensor.unsqueeze(1)` |
| **Matrix Ops** | Matrix Multiplication | — | `a @ b` or `np.matmul(a, b)` | `a @ b` or `torch.matmul(a, b)` |

#9.3 Creating Tensor

#### Automatically Generated Tensors With Types

In [3]:
empty_tensor = torch.empty(2,3) # var = torch.empty(r, c)
print(f"Tensor data structure with garbage dataset: \n{empty_tensor}")

zero_tensor = torch.zeros(2,3) # var = torch.zeros(r, c)
print(f"\nTensor data structure with zeros: \n{zero_tensor}")

ones_tensor = torch.ones(2,3) # var = torch.ones(r, c)
print(f"\nTensor data structure with ones: \n{ones_tensor}")

random_tensor = torch.rand(2,3) # var = torch.rand(r, c)
print(f"\nTensor data structure with random values: \n{random_tensor}")

# for research paper, to get the same random output always
torch.manual_seed(3)
random_tensor_rp = torch.rand(2,3)
print(f"\nTensor data structure with random reproducible values: \n{random_tensor_rp}")
# rerun it to check how random_tensor changes each time but random_tensor_rp stays the same

# Identity Matrix
identity_tensor = torch.eye(3) # var = torch.eye(n)
print(f"\nTensor data structure with identity matrix: \n{identity_tensor}")

# Tensor values according to a range
range_tensor = torch.arange(start=0, end=5, step=1) # var = torch.arange(start, end, step), (0, 5, 1) will also do the same
print(f"\nTensor data structure with range values: \n{range_tensor}")

# Linspace
linspace_tensor = torch.linspace(start=0.1, end=1, steps=10) # var = torch.linspace(start, end, steps)
print(f"\nTensor data structure with linspace values: \n{linspace_tensor}")





Tensor data structure with garbage dataset: 
tensor([[1.1491e-43, 1.8217e-44, 9.8091e-45],
        [9.8091e-45, 1.9618e-44, 3.3631e-44]])

Tensor data structure with zeros: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Tensor data structure with ones: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Tensor data structure with random values: 
tensor([[0.6704, 0.9035, 0.0242],
        [0.0741, 0.5467, 0.2890]])

Tensor data structure with random reproducible values: 
tensor([[0.0043, 0.1056, 0.2858],
        [0.0270, 0.4716, 0.0601]])

Tensor data structure with identity matrix: 
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Tensor data structure with range values: 
tensor([0, 1, 2, 3, 4])

Tensor data structure with linspace values: 
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


#### Manually Generated Tensors

In [4]:
# Manually Made Tensors
# manual_tensor = torch.tensor([ [row-1], [row-2] ]) # 3 columns
manual_tensor = torch.tensor(
    [
        [2,3,3],
        [5,6,4],
        [7,8,5]
    ]
)
print(f"\nTensor data structure with manual values: \n{manual_tensor}")


Tensor data structure with manual values: 
tensor([[2, 3, 3],
        [5, 6, 4],
        [7, 8, 5]])


#9.4 Shape of Tensors

### New tensor with prev_tensor's shape

In [5]:
# Tensor Shape
print(f"The shape of the Manual Tensor is: {manual_tensor.shape}")

# type_like (prev_tensor_name) : Making another tensor following the shape -> new_tensor = torch.empty/zeros/ones_like(prev_tensor)
empty_like_tensor = torch.empty_like(manual_tensor)
print(f"\nTensor data structure with garbage dataset: \n{empty_like_tensor}")
print("Output full of garbage data following the shape of the manual_tensor")

zeros_like_tensor = torch.zeros_like(manual_tensor) # same goes for ones_like_tensor
print(f"\nTensor data structure with zeros: \n{zeros_like_tensor}")
print("Output full of zeros following the shape of the manual_tensor")

The shape of the Manual Tensor is: torch.Size([3, 3])

Tensor data structure with garbage dataset: 
tensor([[137039942847888, 137039942847888,       950204320],
        [      867605824,               0,       950263136],
        [              0,               0,               0]])
Output full of garbage data following the shape of the manual_tensor

Tensor data structure with zeros: 
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
Output full of zeros following the shape of the manual_tensor


### Random Tensor with changing dtype with prev shape

In [6]:
# rand_like_tensor
# rand_like_tensor = torch.rand_like(manual_tensor) # this line will throw an error
# Range of rand_tensor = (0,1); so it includes float. But my prev_tensor manual_tensor only contains int type numbers. So, to make it work you'll explicitly need to mention the data type
rand_like_tensor = torch.rand_like(manual_tensor, dtype=torch.float) # u can also write float32, float16 instead of plain float
print(f"\nTensor data structure with random values: \n{rand_like_tensor}")
print("Output full of random values following the shape of the manual_tensor")


Tensor data structure with random values: 
tensor([[0.7719, 0.7437, 0.5944],
        [0.8879, 0.4510, 0.7995],
        [0.1498, 0.4015, 0.0542]])
Output full of random values following the shape of the manual_tensor


# 9.5 Data Type of Tensors

### How to see the datatype: .dtype

In [7]:
print(f"The data type of the Manual Tensor is: {manual_tensor.dtype}")
# rand_like_tensor2 = torch.rand_like(manual_tensor, dtype=torch.int)
# print(f"\nTensor data structure with random values: \n{rand_like_tensor2}")
# print("Output full of random values following the shape of the manual_tensor")

The data type of the Manual Tensor is: torch.int64


In [8]:
print(f"The data type of the Random Tensor is: {rand_like_tensor.dtype}")

The data type of the Random Tensor is: torch.float32


Here one thing to notice, it is saying float64, the optimal one as it doesnt mention the float type in the prev code cell where is was generated.
But if u pushed something like float16, it will compress and will show you float16.

### Conversion of data type


You can change the int type to float type or 2.0 kinda float to 2 kinda int type. But cant change random (0, 1) float to integers.

In [9]:
type_tensor = torch.tensor ([ [1.0, 2.0, 3.0] ])
print(type_tensor)
print(f"Initial Data Type of this tensor: {type_tensor.dtype}")
type_tensor_int = torch.tensor (type_tensor, dtype=torch.int)
print(f"\n.int: Changed Data Type of this tensor: {type_tensor_int.dtype}")
print(type_tensor_int)
type_tensor_float = torch.tensor (type_tensor_int, dtype=torch.float)
print(f"\n.float: Changed Data Type of this tensor: {type_tensor_float.dtype}")
print(type_tensor_float)

tensor([[1., 2., 3.]])
Initial Data Type of this tensor: torch.float32

.int: Changed Data Type of this tensor: torch.int32
tensor([[1, 2, 3]], dtype=torch.int32)

.float: Changed Data Type of this tensor: torch.float32
tensor([[1., 2., 3.]])


/tmp/ipykernel_1034/1376010623.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  type_tensor_int = torch.tensor (type_tensor, dtype=torch.int)
/tmp/ipykernel_1034/1376010623.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  type_tensor_float = torch.tensor (type_tensor_int, dtype=torch.float)


The error here is a warning. Don't worry too much about it. If it bothers you that much, without copying the name of the tensors you can copy the whole tensor and paste it each time at the name of the place of each tensors.

In [10]:
# The easier way: new_tensor = prev_tensor.to(torch.wanted_dtype)
# We already know type_tensor was a float (1.0, 2.0...)
dtype_by_to = type_tensor.to(torch.int)
print(f"Changed Data Type of this tensor: {dtype_by_to.dtype}")

Changed Data Type of this tensor: torch.int32


#9.6 Math Scalar Operations

| Operation | Math Symbol | Python Operator Shortcut | Functional Equivalent (PyTorch) | Functional Equivalent (TensorFlow) | Result on T |
|---|---|---|---|---|---|
| Addition | `+` | `T + 2` | `torch.add(T, 2)` | `tf.add(T, 2)` | `[12.0, 17.5, -2.2]` |
| Subtraction | `−` | `T - 5` | `torch.sub(T, 5)` | `tf.subtract(T, 5)` | `[5.0, 10.5, -9.2]` |
| Multiplication | `×` | `T * 3` | `torch.mul(T, 3)` | `tf.multiply(T, 3)` | `[30.0, 46.5, -12.6]` |
| True Division | `÷` | `T / 2` | `torch.div(T, 2)` | `tf.divide(T, 2)` | `[5.0, 7.75, -2.1]` |
| Exponentiation | `xʸ` | `T ** 2` | `torch.pow(T, 2)` | `tf.pow(T, 2)` | `[100.0, 240.25, 17.64]` |
| Floor Division | `⌊x/y⌋` | `T // 3` | `torch.floor_divide(T, 3)` | `tf.math.floordiv(T, 3)` | `[3.0, 5.0, -2.0]` |
| Modulo (Remainder) | `%` | `T % 4` | `torch.remainder(T, 4)` | `tf.math.mod(T, 4)` | `[2.0, 3.5, 3.8]` |
| Negation | `−x` | `-T` | `torch.neg(T)` | `tf.negative(T)` | `[-10.0, -15.5, 4.2]` |


In [11]:
T = torch.tensor([10.0, 15.5, -4.2])

# Addition
T_add = T + 2
print(f"Addition: {T_add}")

# Subtraction
T_sub = T - 5
print(T_sub.to(torch.int))
print(T_sub)

Addition: tensor([12.0000, 17.5000, -2.2000])
tensor([ 5, 10, -9], dtype=torch.int32)
tensor([ 5.0000, 10.5000, -9.2000])


I don't know why it's including 4 digits of zeros.

#9.7 Math Element Wise Operation
| Category | Math / Concept | Operator | PyTorch Function | Behavior / Example |
| :--- | :--- | :--- | :--- | :--- |
| **Arithmetic** | Addition | `+` | `torch.add(A, B)` | $A_i + B_i$ |
| | Subtraction | `-` | `torch.sub(A, B)` | $A_i - B_i$ |
| | Multiplication | `*` | `torch.mul(A, B)` | Element-wise product (Hadamard product) |
| | Exponentiation | `**` | `torch.pow(A, B)` | $A_i^{B_i}$ |
| **Division** | True Division | `/` | `torch.div(A, B)` | Floating-point division (e.g., `5 / 2 = 2.5`) |
| | Floor Division | `//` | `torch.floor_divide(A, B)` | Divides and rounds down towards negative infinity (`5 // 2 = 2`) |
| | Modulus (Python) | `%` | `torch.remainder(A, B)` | Remainder following Python semantics (sign matches divisor $B$) |
| | Modulus (C-style) | — | `torch.fmod(A, B)` | Remainder following C/C++ semantics (sign matches dividend $A$) |
| **Rounding** | Round Nearest | — | `torch.round(A)` | Rounds to nearest integer (ties round to nearest **even** integer) |
| | Floor | — | `torch.floor(A)` | Rounds down to nearest integer ($\lfloor x \rfloor$) |
| | Ceiling | — | `torch.ceil(A)` | Rounds up to nearest integer ($\lceil x \rceil$) |
| | Truncate | — | `torch.trunc(A)` | Drops decimal part, rounds toward zero |
| **Comparison** | Element-wise Max | — | `torch.maximum(A, B)` | Returns $\max(A_i, B_i)$ at each index |
| | Element-wise Min | — | `torch.minimum(A, B)` | Returns $\min(A_i, B_i)$ at each index |
| | Equality | `==` | `torch.eq(A, B)` | Boolean tensor (`True` where $A_i = B_i$) |
| | Float Tolerance | — | `torch.isclose(A, B)` | Boolean tensor (checks $\|A - B\| \le \text{atol} + \text{rtol} \times \|B\|$) |

In [12]:
# Declare 2 tensors
a = torch.tensor([
    [1, 2, 3],
    [ 4, 5, 6]
])

b = torch.tensor([
    [7, 8, 9],
    [10, 11, 12]
])

Experiment yourself with the written note

In [13]:
a + b

tensor([[ 8, 10, 12],
        [14, 16, 18]])

Note for the previous cell:
TOOK 2-3 SECONDS

####Clamp

In [14]:
d = torch.clamp(a+b, min=11, max=15) # number below 11 will turn to 11, number above 15 will turn into 15
d

tensor([[11, 11, 12],
        [14, 15, 15]])

#9.8 Math Reduction Operations
# PyTorch Tensor Reduction Operations

Reduction operations aggregate data along one or more dimensions, producing smaller tensors or scalar values.

| Category | Operation | PyTorch Function / Method | Example Code | Behavior / Notes |
| :--- | :--- | :--- | :--- | :--- |
| **Summation** | Total Sum | `torch.sum(A)` | `A.sum()` | Sum of all elements in tensor $A$. |
| | Row-wise Sum | `torch.sum(A, dim=1)` | `A.sum(dim=1)` | Collapses columns; sums across each row (shape $[M, N] \to [M]$). |
| | Column-wise Sum | `torch.sum(A, dim=0)` | `A.sum(dim=0)` | Collapses rows; sums across each column (shape $[M, N] \to [N]$). |
| | Keep Dimensions | `torch.sum(A, dim=0, keepdim=True)` | `A.sum(dim=0, keepdim=True)` | Keeps original rank (shape $[M, N] \to [1, N]$), useful for broadcasting. |
| **Averages & Products** | Mean (Average) | `torch.mean(A)` | `A.mean(dim=0)` | Requires floating-point or complex dtype. Computes $\frac{1}{N}\sum x_i$. |
| | Median | `torch.median(A)` | `A.median(dim=0)` | Returns the middle value (or value at index $\lfloor (N-1)/2 \rfloor$). |
| | Product | `torch.prod(A)` | `A.prod(dim=1)` | Computes product of all elements ($\prod x_i$). |
| **Statistics** | Standard Deviation | `torch.std(A)` | `A.std(dim=0, correction=1)` | Sample std dev (Bessel's correction $N-1$ default). Set `correction=0` for population. |
| | Variance | `torch.var(A)` | `A.var(dim=0, correction=1)` | Sample variance ($\sigma^2$). Set `correction=0` for population variance. |
| **Extrema & Indices** | Global Min / Max | `torch.min(A)` / `torch.max(A)` | `A.min()`, `A.max()` | Returns the single smallest or largest scalar value in tensor. |
| | Min / Max by Dim | `torch.min(A, dim=0)` / `torch.max(A, dim=0)` | `values, indices = A.max(dim=0)` | Returns a named tuple `(values, indices)` along specified dimension. |
| | Index of Min | `torch.argmin(A)` | `A.argmin(dim=1)` | Index of minimum value. Unrolled index if `dim` is omitted. |
| | Index of Max | `torch.argmax(A)` | `A.argmax(dim=1)` | Index of maximum value. Unrolled index if `dim` is omitted. |
| **Cumulative** | Cumulative Sum | `torch.cumsum(A, dim=1)` | `A.cumsum(dim=1)` | Returns cumulative sum along dimension (preserves tensor shape). |
| | Cumulative Product | `torch.cumprod(A, dim=0)` | `A.cumprod(dim=0)` | Returns cumulative product along dimension (preserves tensor shape). |

---

### Row / Column-wise Broadcasting Arithmetic

To perform row-wise or column-wise addition/subtraction between a 2D matrix $A$ (shape $[M, N]$) and a 1D tensor $B$:

* **Row-wise operation (apply $B$ to each row):**
  * Tensor $B$ must have shape $[N]$ or $[1, N]$.
  * Code: `A + B` or `A - B` (Broadcasting matches the trailing dimension automatically).
* **Column-wise operation (apply $B$ to each column):**
  * Tensor $B$ must have shape $[M, 1]$ (or unsqueezed explicitly).
  * Code: `A + B.unsqueeze(1)` or `A - B.unsqueeze(1)`.

Tensor for experimenting

In [15]:
f = torch.randint( size = (2,3), low = 1, high = 10, dtype = torch.float32 )
f

tensor([[5., 4., 7.],
        [9., 9., 1.]])

#9.9 Math Matrix Operations

In PyTorch, **element-wise multiplication (`*`) is completely different from matrix multiplication (`@`)**.

### Matrix Multiplication (Dot Products)

| Operation | Operator | PyTorch Function | Behavior & Notes |
| :--- | :--- | :--- | :--- |
| **Vector Dot Product** | — | `torch.dot(v1, v2)` | Strictly for 1D tensors (vectors). Computes $\sum v_{1i} v_{2i}$. |
| **Matrix Multiplication** | `@` | `torch.matmul(A, B)` | Standard matrix multiplication. Supports broadcasting for higher dimensions. |
| **Strict 2D MatMul** | — | `torch.mm(A, B)` | Strictly for 2D matrices (no broadcasting). Faster if you know both are exactly 2D. |
| **Batch MatMul** | — | `torch.bmm(A, B)` | For 3D tensors: `[batch, n, m] @ [batch, m, p] -> [batch, n, p]`. |
| **Determinant** | — | `torch.det(A) or torch.linalg.det(A)` | For square 2D matrices or batches of square 2D matrices. |
| **Inverse** | — | `torch.inverse(A) or torch.linalg.inv(A)` | For 1D matrices. |

---

#### Matrix Inverse Formulas (for hand calculations)

##### 1. General Formula ($n \times n$)

$$A \cdot A^{-1} = A^{-1} \cdot A = I$$


$$A^{-1} = \frac{1}{\det(A)} \operatorname{adj}(A)$$

> **Requirement:** The matrix must be non-singular, meaning $\det(A) \neq 0$.

##### 2. Specific Formula ($2 \times 2$ Matrix)
Given a $2 \times 2$ matrix: $\det(A) = ad - bc$:

$$A^{-1} = \frac{1}{ad - bc} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}$$


---

### Transposition & Permutation

| Operation | PyTorch Code | Behavior |
| :--- | :--- | :--- |
| **Simple Transpose (2D)** | `A.T` or `A.t()` | Flips rows and columns of a 2D matrix ($A^T$). |
| **Specific Dim Transpose**| `torch.transpose(A, dim0, dim1)` | Swaps two specific dimensions (useful for 3D+ tensors). |
| **Permute All Dims** | `A.permute(2, 0, 1)` | Rearranges all dimensions to a specified order (common in image processing). |

---

### Advanced Linear Algebra (`torch.linalg`)
PyTorch groups standard linear algebra functions under the `torch.linalg` module, closely mirroring `numpy.linalg`.

| Concept | PyTorch Function | Output / Notes |
| :--- | :--- | :--- |
| **Inverse** | `torch.linalg.inv(A)` | Computes the multiplicative inverse of a square matrix ($A^{-1}$). |
| **Pseudo-Inverse** | `torch.linalg.pinv(A)` | Moore-Penrose pseudoinverse (for non-square matrices). |
| **Determinant** | `torch.linalg.det(A)` | Computes the determinant of a square matrix. |
| **Matrix Norm** | `torch.linalg.norm(A)` | Computes the Frobenius norm (or others depending on `ord` argument). |
| **Solve Linear System** | `torch.linalg.solve(A, B)` | Solves $AX = B$ for $X$. Much faster and more stable than computing $A^{-1}B$. |
| **Eigenvalues/Vectors** | `torch.linalg.eig(A)` | Returns a named tuple `(eigenvalues, eigenvectors)`. |

---

### ⚠️ Common Pitfall: `reshape` vs. `transpose`

* **`A.transpose()`** mathematically alters the data layout (flips axes).
* **`A.reshape()`** keeps the same data sequence in memory but changes how it is grouped.
* **If you want a matrix transpose, NEVER use `.reshape()`. Use `.T`.**

```python
# Quick code example: Linear Layer Math
import torch

inputs = torch.randn(32, 128)  # Batch of 32, 128 features
weights = torch.randn(64, 128) # 64 output neurons, 128 input weights
bias = torch.randn(64)         # 64 bias terms

# Y = X @ W^T + b
outputs = inputs @ weights.T + bias
# outputs shape: [32, 64]

In [16]:
torch.manual_seed(2)
g = torch.randint( size = (2,3), low = 1, high = 10)
h = torch.randint( size = (2,3), low = 1, high = 10)
# one fact: if u do the manual seed (2) again before h, then g ~= h
print(f"g: {g}")
print(f"\nh: {h}")

g: tensor([[1, 7, 9],
        [1, 9, 4]])

h: tensor([[1, 5, 9],
        [7, 7, 2]])


Matrix Multipliccation

In [17]:
torch.matmul (g.T, h)

tensor([[ 8, 12, 11],
        [70, 98, 81],
        [37, 73, 89]])

Dot Product

In [18]:
# torch.dot(g, h) # error, 1 dimensional tensor needed, ours are 2 dimensional (num of features)
v1 = torch.tensor([1,2,3])
v2 = torch.tensor([4,5,6])
torch.dot(v1, v2)

tensor(32)

## Dimension Discussioon
📐 Tensor Dimensions vs. Dataset Features

---

## 1. In PyTorch / Linear Algebra (Tensors)
In PyTorch, **dimension** refers to the **number of axes** (or `ndim`), not the size of the rows or columns.

* **0D Tensor (Scalar):** `torch.tensor(5)` — 0 axes. - just a number (5)
* **1D Tensor (Vector):** `torch.tensor([1, 2, 3])` — 1 axis (length 3).
* **2D Tensor (Matrix):** `torch.tensor([[1, 2], [3, 4]])` — 2 axes (rows and columns).
  * Axis 0 = Rows
  * Axis 1 = Columns
* **3D Tensor (e.g., Image Batch):** Shape `(32, 28, 28)` — 3 axes (Batch size, Height, Width).

---

## 2. In Data Science / Machine Learning (Datasets)
In a tabular dataset, **dimension = number of features (columns)**.

* **Rows ($N$):** Number of samples or data points.
* **Columns ($D$):** Number of features (dimensions).
* *Example:* A CSV file with 10,000 rows and 50 feature columns is a **50-dimensional dataset**.

---

| Context | What "Dimension" Means | Example |
| :--- | :--- | :--- |
| **PyTorch / NumPy** | Number of axes / shape length (`tensor.ndim`) | Shape `(2, 3)` = **2D Tensor** |
| **Data Science / ML** | Number of columns / features | 50 feature columns = **50-Dimensional Data** |

#9.10 Comparison Operation (whole matrix)

- i > j
- i < j
- i == j
- i != j

In [19]:
i = torch.randint(low=0, high=10, size = (2,3))
j = torch.randint(low=0, high=10, size = (2,3))
print(f"i: {i}")
print(f"\nj: {j}")

i: tensor([[9, 5, 5],
        [3, 9, 7]])

j: tensor([[6, 0, 0],
        [2, 3, 1]])


In [20]:
i != j

tensor([[True, True, True],
        [True, True, True]])

#9.11 Special Function
- torch.log(k) : e base log
- torch.exp(k) : e to the power k
- Activation Functions:
  - **Sigmoid:** torch.sigmoid (k) $$\sigma(x) = \frac{1}{1 + e^{-x}}$$ (Outputs $[0, 1]$)
  - **ReLU:** torch.relu (k) $$\text{ReLU}(x) = \max(0, x)$$ (Outputs $[0, \infty)$)
  - **Softmax:** torch.softmax (k, dim=1)$$\operatorname{Softmax}(x_i) = \frac{e^{x_i}}{\sum_{j} e^{x_j}}$$ (Outputs probability distribution)

---

### `torch.softmax(input, dim)`

Softmax normalizes numbers so that they sum to `1.0`. The `dim` parameter specifies **which axis to normalize over**:

* `dim=1` (or `dim=-1`): Computes probabilities **per row** (across columns). Standard for multi-class predictions. **Sample's Class Probabilities**
* `dim=0`: Computes probabilities **per column** (across rows/batches). **not very useful in prediction**

In [21]:
k = torch.tensor([10,20,30], dtype = torch.float32) # softmax requires float dtype
torch.softmax(k, dim=0) # dim 0 or -1, as no col or row for 1D tensor, only 1 single axis. so dim = 0, the first and only available axis. dim = 1 means second axis which is non existent

tensor([2.0611e-09, 4.5398e-05, 9.9995e-01])

#9.12 Inplace Operations
###Reason:

If u have a, then b = a + 5, so a new variable space will be created and saving this will use ur memory. SO, we do inplace operations to prevent memory waste.

- m.add_(n): m will be m + n, so, m = m +n
- torch.relu_(m) or m.relu_() : m = torch.relu(m)

#9.13 Copying Tensor & Memory Discussion

##Shallow Copy:
- code: a = b
- shares the same memory. Same ID (memory address).
- Near Zero memory cost
- if u change one, the other will be changed too accordingly.
##Deep Copy or independent memory:
- code:
  - b = a.clone() (with preserving autograd history)
  - b = a.clone().detach() (standard for complete isolated copy)
  - b = a.copy.deepcopy() (also works in Python, pythonic way)

- will allocate new memory for b
- so will take the extra memory. Potentiality of memory waste.
- changes will be separate.

In [22]:
a = torch.tensor( [1, 2, 3] )
print(f"The first a tensor: {a}")
b = a # shallow copy
# b = a.clone() # deep copy (still not standard)

# changing b
b [1] = 10
b

print(f"Tensor after changing b: {a}")

The first a tensor: tensor([1, 2, 3])
Tensor after changing b: tensor([ 1, 10,  3])
